[package]
name = "swaysome"
version = "1.0.0"
authors = ["Skia <skia@hya.sk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
serde_json = "1"
rand = "0.8"
